[tools]
neovim = "latest"
elixir = "latest"
erlang = "latest"
eza = "latest"
go = "latest"
php = "8.4"
node = "latest"
pnpm = "latest"
python = "3.10"
rust = "latest"
usage = "latest"

# Neovim formatters
jq = "latest"
shfmt = "latest"
yamlfmt = "latest"
taplo = "latest"
stylua = "latest"
black = "latest"
